
class SaveFileKeys:
    OUTPUT_FOLDER_PATH = 'OUT_FOLDER_PATH'
    RESULT_FOLDER = 'RES_FOLDER'
    RESULT_FOLDER_TOGGLE = 'RES_FOLDER_TOGGLE'

    # Equipment Settings
    OSCILLOSCOPE_ADDRESS = 'OSC_ADDR'


    # Test Settings
    CUSTOM_LINE_RANGE = 'CUSTOM_LINE_RANGE'
    CUSTOM_LOAD_RANGE = 'CUSTOM_LOAD_RANGE'